spring:
  application:
    name: core-banking
  datasource:
    url: jdbc:mysql://${DB_URL}/${DATABASE_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

exchange:
    auth-key: ${EX_API_KEY}